  server:
    port: 9191
  spring:
    application:
      name: API-GATEWAY
    cloud:
      gateway:
        routes:
          - id: studentSERVICE
            uri: lb://studentSERVICE
            predicates:
              - Path= /students/**
          - id: teacherSERVICE
            uri: lb://teacherSERVICE
            predicates:
              - Path= /enseignant/**
          - id: administrationSERVICE
            uri: lb://administrationSERVICE
            predicates:
              - Path= /administrator/**
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true

